plugin: aws_ec2
regions:
  - us-east-1
filters:
  "tag:Role": ["jenkins-master", "jenkins-slave"]
keyed_groups:
  - key: tags.Role
hostnames:
  - private-ip-address
compose:
  ansible_user: ubuntu                             # Ubuntu AMI user (not ec2-user)
  ansible_ssh_private_key_file: /opt/dpo.pem
